version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfiles/api.yml
    ports:
      - "5002:5002"
    expose:
      - "5002"
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./:/home/app
    environment:
      - FLASK_APP=main.py
      - FLASK_SECRET=${FLASK_SECRET}
      - FLASK_DEBUG=1
      - PRODUCTION=${PRODUCTION}
    env_file:
      - 'postgres.env'
    depends_on:
      - redis
      - postgres
    networks:
      - default
  processor:
    build:
      context: .
      dockerfile: Dockerfiles/processor.yml
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./:/home/app
    env_file:
      - 'postgres.env'
    depends_on:
      - redis
      - postgres
    networks:
      - default
  redis:
    image:
      redis
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - "6379"
    networks:
      - default
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - 'postgres.env'
    networks:
      - default

networks:
  default:

volumes:
  postgres_data:
