version: '3'

services:
  api:
    build:
        context: .
        dockerfile: Dockerfiles/api.yml
    ports:
      - "5002:5002"
    expose:
      - "5002"
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./:/home/app
    environment:
      - FLASK_APP=main.py
      - FLASK_SECRET=${FLASK_SECRET}
      - FLASK_DEBUG=1 
    depends_on:
      - redis
    networks:
      - default
  processor:
    build:
        context: .
        dockerfile: Dockerfiles/processor.yml
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./:/home/app
    depends_on:
      - redis
    networks:
      - default
  redis:
    image:
      redis
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - "6379"
    networks:
      - default

networks:
  default:
